-- ==============================================================================
-- Seed Data E-Rapot Tahfidz dari 'Absensi Diniyah.xlsx' (TP 2026/2027)
-- Total Santri: 105 (Nama sudah Proper Case)
-- ==============================================================================

-- 1. Tahun Ajaran Default
INSERT INTO tahun_ajaran (id, nama, semester, is_active)
VALUES ('a0000000-0000-0000-0000-000000000001', '2026/2027', 'الأول', true)
ON CONFLICT DO NOTHING;

-- 2. Data Santri Master (Berdasarkan NIS dan Kelas Bahasa Arab)
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26001', 'Afifah Sidqia', 'الأول', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26002', 'Aliyah Syafira', 'الأول', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26003', 'Asmaul Husna Aryani', 'الأول', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26004', 'Aufa Azalia', 'الأول', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26005', 'Balqis Sari Mustika', 'الأول', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26006', 'Bening Najma Ismail', 'الأول', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26007', 'Hilmi Hafsoh', 'الأول', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26008', 'Keysa Assabiya Rafifa', 'الأول', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26009', 'Khayla Najmy Ardini', 'الأول', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26011', 'Qonita Azzahra', 'الأول', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26012', 'Safa Indri Yani', 'الأول', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26013', 'Shazia Jasmine Az-Zahwa', 'الأول', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26014', 'Shela Fahira Suhendar', 'الأول', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26015', 'Shely Andini Suhendar', 'الأول', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26016', 'Syaza Auni Prasetyo', 'الأول', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26017', 'Tatu Husna Nurul Hapidah', 'الأول', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26018', 'Ulfatujjadidah', 'الأول', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26019', 'Vannesia Putri', 'الأول', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26020', 'Yuyun Adya Ghraini', 'الأول', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26021', 'Zian Rameyza', 'الأول', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('25001', 'Ainayya Nuriel Ihsan', 'الثاني', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('25002', 'Annisa Hidayah Nurussunnah', 'الثاني', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('25003', 'Atika Aisyah', 'الثاني', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('25004', 'Aulia Silvina Muklis', 'الثاني', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('25005', 'Az-Zahra Salsabila', 'الثاني', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('25006', 'Chila Miftahul Janah', 'الثاني', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('25007', 'Dechila Fadillah Setiawan', 'الثاني', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('25008', 'Elin Setia Wati', 'الثاني', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('25009', 'Fega Aulia Putri', 'الثاني', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('25010', 'Fhisnia Anisa Sholehah', 'الثاني', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('25011', 'Hanifa', 'الثاني', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('25012', 'Iqlima Izzatul Hasanah', 'الثاني', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('25013', 'Jihan Qonita Khamelia', 'الثاني', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('25015', 'Nadyah Artala Marsid', 'الثاني', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('25016', 'Naiyla Salsabrina', 'الثاني', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('25017', 'Qonitatun Hafizhoh', 'الثاني', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('25018', 'Rayya Faiza Balqis', 'الثاني', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('25019', 'Warisa', 'الثاني', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26010', 'Nazia Azahwa', 'الثاني', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24001', 'Akilla Nasywa', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24002', 'Alisha Nurmala Dewi', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24003', 'Al-Lathifa Pria Hanindyta', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24004', 'Annisa Balqis Azzahra', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24005', 'Annisa Nabilla Alfania', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24007', 'Assyfa Rahma Irawadi', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24008', 'Dzakia Rihadatul Adhwa', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24009', 'Fina Fadhilatul Muthi''ah', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24010', 'Habibah Hasna Sukoco', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24011', 'Izza Rahma Wati', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24012', 'Jamilatun Humairo', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24013', 'Jean Sentari', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24014', 'Kinar Kirana Chotimah', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24016', 'Leila Iren Suprapto', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24017', 'Lutvy Al-Muslimah', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24018', 'Miftha Talita Zakiah', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24019', 'Nabila Felicia', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24020', 'Nafisatun Najuwa', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24022', 'Raqiqa Nurin Mahira', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24023', 'Rifta Ikhda Adha Maulida', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24024', 'Saffanah Muzdhalifah', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24025', 'Salwa Putri Azkia', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24026', 'Siti Novianti Qholifah', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24027', 'Sunur Najiah Hashifah', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24029', 'Tiara Hesti Audina', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24030', 'Umi Nur Hidayah', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24031', 'Unzila Istiqomah', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24032', 'Zahra Saputri', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('24033', 'Luluk Adelia Lutfia', 'الثالث', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('23001', 'Aziza', 'الرابع', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('23002', 'Aziza Latif', 'الرابع', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('23017', 'Tirtana Prasetyo', 'الرابع', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('23018', 'Vebika Sandi Safitri', 'الرابع', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('23021', 'Zayyini Husna Abida', 'الرابع', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26022', 'Alya Zulaini', 'الرابع', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26023', 'Brilliyan Ramadhan', 'الرابع', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26024', 'Khaisya Efendi Putri', 'الرابع', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26025', 'Marisa Septia Bella', 'الرابع', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('26026', 'Saskia Alya Ramadhani', 'الرابع', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('25014', 'Nadin Hasheiva Zahrani', 'الرابع', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('22007', 'Chika Kholifatul Latiffa', 'الخامس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('22009', 'Dewi Hasanah', 'الخامس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('22014', 'Khoirun Nis''A', 'الخامس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('22017', 'Kinanti Diva Meisya', 'الخامس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('22018', 'Nabila Fatin', 'الخامس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('22022', 'Natzwa Fitriani', 'الخامس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('22023', 'Nurma Khoirunnisa', 'الخامس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('22028', 'Sara Janina Arifin', 'الخامس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('22030', 'Suci Romadhona', 'الخامس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('22033', 'Zaskia Rahma Isnaini', 'الخامس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('22011', 'Eka Wahyu Nur Kholimah', 'الخامس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('22026', 'Rifa Rumaisya Kamal', 'الخامس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('21001', 'Aulia Salsabila Lubis', 'السادس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('21002', 'Dina Febriyanti', 'السادس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('21003', 'Dinah Syakira', 'السادس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('21006', 'Dzulfa Salsabila', 'السادس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('21010', 'Jihan Nabila', 'السادس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('21011', 'Khanza Nur Rahma Al Magh Firah', 'السادس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('21013', 'Milani Az Zahra', 'السادس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('21016', 'Rumaisha Al-Hawra', 'السادس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('21017', 'Sab''Atul Mukharomah', 'السادس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('21018', 'Sifa Khalis Dahlina', 'السادس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('21019', 'Sifa Khanif Azzahra', 'السادس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('21021', 'Sokhivatul Izah', 'السادس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('21025', 'Zahirotun Nafisah', 'السادس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
INSERT INTO santri (nis, nama, kelas, jenis_kelamin, status) VALUES ('21027', 'Nazwa Putri Dwi Aulia', 'السادس', 'P', 'aktif') ON CONFLICT (nis) DO UPDATE SET nama = EXCLUDED.nama, kelas = EXCLUDED.kelas;
